$(document).ready(function(){
  $('button#kuiz').click(function(){
    $('#description').hide();
    $('#quest').show();
  })
  $('a#a1').click(function(){
    $('#q2').show();
    $('#q1').hide();
  })
  $('a#a2').click(function(){
    $('#q2').show();
    $('#q1').hide();
  })
  $('a#b1').click(function(){
    $('#q3').show();
    $('#q2').hide();
  })
  $('a#b2').click(function(){
    $('#q3').show();
    $('#q2').hide();
  })
  $('a#b3').click(function(){
    $('#q3').show();
    $('#q2').hide();
  })
  $('a#b4').click(function(){
    $('#q3').show();
    $('#q2').hide();
  })
  $('a#c1').click(function(){
    $('#q4').show();
    $('#q3').hide();
  })
  $('a#c2').click(function(){
    $('#q5').show();
    $('#q3').hide();
  })
})
